### ISSUE TITLE
[BUG] - Only one wiki page link allowed per a page

### ISSUE THREAD

**Issue by brettsaunders21** [CraftoryStudios/website#11]
## :round_pushpin: Description (REQUIRED)

On any wiki page if you insert more than one link using [[link]] then the first link will work as intended and the second won't.

## :bulb: Expected behavior (REQUIRED)

Both links correctly link to the page if clicked and show a hover over image of the page in question if one exists. Also the [ ] square brackets around the link should be hidden.

## :computer: Link to page issue appears on (REQURIED)

The issue can be seen on the Getting Started page with the links to Foundry
https://craftory.studio/craftory-tech/wiki/getting-started.html

**Comment by TheBusyBiscuit** [comment]
So, I looked a little into this and the reason [[ Foundry ]] is not working is because of the `(Non Electric Version)` behind it.

```markdown
[name](url]
```

is the syntax of making a link in markdown.
And since the markdown is parsed before the wiki variables get handled, `[[ Foundry ]] (Non Electric Version)` is converted into `[Foundry]` (with a link to the non-existing url "https://Non-Electric-Version".

Perhaps adding `&nbsp;` inbetween the two might solve the issue, or just simply refraining from using brackets right after a wiki link.

**Comment by brettsaunders21** [comment]
Awesome, thanks for looking into this @TheBusyBiscuit. Will give it a go fixing this.
