### ISSUE TITLE
Discord Widget not maintaining dark theme on reload

### ISSUE THREAD

**Issue by brettsaunders21** [CraftoryStudios/website#20]
## :round_pushpin: Description (REQUIRED)

When going back to the main page of the Craftory Studios website the Discord widget always reverts back to light theme. 
![image](https://user-images.githubusercontent.com/32368716/100397293-ccfb6600-3040-11eb-812c-6a500047d65d.png)

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Head to https://craftory.studio/
2. Toggle Dark mode on
3. Discord widget and page changes to dark mode
4. Ensure cookies enabled
5. Reload page
6. Discord Widget theme reset

## :bulb: Expected behavior (REQUIRED)

6. Discord widget maintains dark mode

## :computer: Link to page issue appears on (REQURIED)

https://craftory.studio/

**Comment by TheBusyBiscuit** [comment]
Yeah, I noticed that previously. The problem here is because of concurrency.
The element actually **does** update correctly.
It's just that discord's answer for the light theme sometimes arrives after the answer for the dark theme.
*Or simply put, we update the url too fast*

A simple solution for this would be to completely set via iframe src via script and simply leave it empty in the dom. Not exactly best practice though.
